### PR TITLE
Use GET method to fetch the GHontent's content

### PR DESCRIPTION
**Pull request by Shredder121**
This is a little more cache-friendly.

Let me know what you think.

### CODE REVIEW

**Comment by kohsuke** [comment]
I believe this is already addressed in e0b109cba6faa84813a528880dbf3923c1b86058

**Comment by Shredder121** [comment]
It unfortunately isn't.
Only the `HttpURLConnection.method` was set by that change. Not the `Requester.method`.

This means that `Requester.method` is still set to `POST`, `isMethodWithBody` will return true, and `uc.setDoOutput(true)` will be called.

I use Okhttp, and their [HttpURLConnectionImpl's method changes to `POST` if you tell it to open a stream to write to](http://grepcode.com/file/repo1.maven.org/maven2/com.squareup.okhttp/okhttp-urlconnection/2.0.0/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java#292).

**Comment by kohsuke** [comment]
Thanks, that explains. Now I claim dbc79f8c423749311495cb548c1a9cda1d8638cf fixes it!

**Comment by Shredder121** [comment]
I indeed verified that it fixed it, thanks!
So I take it my PR is no longer necessary?

When can I expect to see this released?

**Comment by Shredder121** [comment]
@kohsuke when can I expect to see this released?

**Pull request closed without merging**
