### PR TITLE
#215 fix read() failure with private repos

### LINKED ISSUE #215: GHContent.read() is broken due to incorrect HTTP Method
```GHContent.read()``` issues the request as POST rather than GET.  This is fine for URLs that do not
require authentication.  However, when ```download_url``` links are returned that have tokens in the query string, the corresponding POST fails.

Presumably it fails because on the remote end, the query string parameters of the POST request are not honored.

This issue would never be detected if testing happens against a public GitHub URL.

### PR DESCRIPTION
**Pull request by if6was9**
This fixes #215

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Should the PR also modify <code> asHttpStatusCode</code>? Otherwise it seems to be quite inconsistent

**Comment by oleg-nenashev** [comment]
There are many such request patterns in the class...

**Comment by if6was9** [comment]
Possibly.  read() is 100% broken on private repos, though.

getContent() works but it is deprecated. 

This does fix the issue and it seems unlikely to cause regression.  
 
I'll add a MockWebServer test if you support it.  OkHttp is used so I suspect it is ok?

**Comment by oleg-nenashev** [comment]
@if6was9 
Any new tests will be appreciated :)

**Comment by oleg-nenashev** [comment]
@if6was9 
Are you waiting for an additional review?

**Pull request merged**
