### PR TITLE
Remove trailing slash when requesting directory content

### PR DESCRIPTION
**Pull request by Shredder121**
I noticed something strange on GitHub's end.

When requesting content from a directory (with a specific ref), you get [ref-specific content][1].

Now look closely what happens when you [add a trailing slash][2].

What is your view on this?

[1]: https://api.github.com/repos/github/developer.github.com/contents/lib/webhooks?ref=21295b477e6727ae09c6691e78fca7a33d28b54d
[2]: https://api.github.com/repos/github/developer.github.com/contents/lib/webhooks/?ref=21295b477e6727ae09c6691e78fca7a33d28b54d

### CODE REVIEW

**Comment by Shredder121** [comment]
Could someone restart the build :smile: 
I first saw a mistake, so pushed a new solution.

**Comment by Shredder121** [comment]
Only merge if it's an issue that we _should_ fix.
And only then I still want to add in a test case.

**Comment by oleg-nenashev** [comment]
I have no strong opinion about the fix, but it looks reasonable to me.
CC @KostyaSha

**Comment by KostyaSha** [comment]
Sorry, have no opinion. Will it be possible to make some test case?

**Comment by Shredder121** [comment]
I did so just now.

**Pull request merged**
