### PR TITLE
Added getHtmlUrl() to GHCommit

### PR DESCRIPTION
**Pull request by zapelin**

### CODE REVIEW

**Comment by recena** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
Is it a new field added to GitHub API?
If yes, I'm aware what happens if this field is missing (e.g. old GitHub Enterprise Instances)

**Comment by recena** [comment]
@oleg-nenashev AFAIK, It is simply ignored.

**Comment by zapelin** [comment]
The oldest enterprise docs I have found is [Enterprise 2.0](https://developer.github.com/enterprise/2.0/v3/repos/commits/)
This filed is present in The Repo Commits API

**Pull request merged**
