### PR TITLE
Add GHPullRequestReview.submitted_at field

### PR DESCRIPTION
**Pull request by rmetzger**
This is a fix for https://github.com/kohsuke/github-api/issues/450

### CODE REVIEW

**Comment by rmetzger** [comment]
Yeah, I think their documentation is out of sync (I also notified GitHub about it).
But the API returns the field: https://api.github.com/repos/kohsuke/github-api/pulls/517/reviews

**Comment by bitwiseman** [comment]
@rmetzger  
Ah, okay, but until it is in the docs, it might change, right? 
Also, what about updatedAt? What should be done about that? 
Maybe the a better solution is to override them and have them throw "NotImplemented"?
I'm open to discussion.

**Comment by rmetzger** [comment]
Before opening this pull request, I reached out to GitHub's support, and they consider this field as stable. Apparently, the team just forgot to document it (and my question to the support was not reason enough for them to fix it :( )

**Comment by rmetzger** [comment]
Thanks a lot for merging!

**Pull request merged**
