### PR TITLE
[JENKINS-45142] Retry connections after getting SocketTimeoutException

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-45142](https://issues.jenkins-ci.org/browse/JENKINS-45142)

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
BTW I get a ton of failures/errors running tests in this component, which I doubt are caused by my changes here.

**Comment by stephenc** [comment]
- [ ] @stephenc

**Comment by KostyaSha** [comment]
In my github plugins i just do retryable executions from Function and that's all.

**Comment by jglick** [comment]
@reviewbybees done

**Comment by jglick** [comment]
> do retryable executions from Function

Yes it is possible to work around from the caller side, but to limit the fix to the known case where a retry is definitely sensible, it would be necessary to inspect `cause`s for `instanceof SocketTimeoutException`.

**Pull request merged**
