### PR TITLE
issue #360: Add support for committing multiple files

### PR DESCRIPTION
**Pull request by siordache**
Implement #360. New classes:
- GHBlobBuilder - [create a blob](https://developer.github.com/v3/git/blobs/#create-a-blob)
- GHTreeBuilder - [create a tree](https://developer.github.com/v3/git/trees/#create-a-tree)
- GHCommitBuilder - [create a commit](https://developer.github.com/v3/git/commits/#create-a-commit)

[This gist](https://gist.github.com/siordache/63b19f515e4db6944e2411265f89e92f) shows how to use the new classes.

### CODE REVIEW

**Comment by siordache** [comment]
@reviewbybees

**Comment by jglick** [comment]
@siordache please do not use the above mention. @kohsuke is I think the only one who can now delete the previous two comments.

**Comment by siordache** [comment]
Oh, sorry. I thought that I should use the above mention to indicate that the PR is ready to be reviewed.

**Comment by KostyaSha** [comment]
This is not a jenkins, this @kohsuke owned library. Unfortunately jenkins plugins depends on it, maybe we should raise the question on forking it, because it causes delays for FOSS users. Only those who work with @kohsuke now can influence on releases speed.

**Comment by jglick** [comment]
Yes, various people have requested that @kohsuke move ownership of this and some other repositories necessary for Jenkins to the @jenkinsci org, or otherwise open up access.

**Pull request merged**
