### PR TITLE
Add information about mirror url if it exist.

### PR DESCRIPTION
**Pull request by vparfonov**
Like https://github.com/apache/tomee

### CODE REVIEW

**Comment by recena** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
maybe needs some polishing, but :+1:

**Comment by recena** [comment]
@oleg-nenashev For example? A test?

**Comment by oleg-nenashev** [comment]
@recena 
No, I mostly think about the API documentation and annotations. BTW it's not important in the current project state. It needs a bulk update.

**Pull request merged**
